name: Count papers in README

on:
  push:
    branches:
      - master

jobs:
  count-items:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Count papers in README
        run: |
          ITEM_COUNT=$(grep -oP '^\s*-\s*\*\*[^*]+\*\*\s*\([0-9]{4}\),\s*[^,]+,[^,]*' README.md | wc -l)
          echo "ITEM_COUNT=$ITEM_COUNT" >> $GITHUB_ENV

      - name: Update paper no. badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0d2ee0d88d518e1a916aef1f8c77a666
          filename: ml4se-paper-no.json
          label: papers
          message: ${{ env.ITEM_COUNT }}
          color: blue
